### ISSUE TITLE
Not working in gnome 3.16

### ISSUE THREAD

**Issue by pedrocs-exo** [zykh/walNUT#1]
Hi Daniele, i have been using walNUT and find it quite useful. Thx for sharing! But ever since I upgraded to Fedora 22 (Gnome 3.16) the extension stopped working. Can you pls fix it? Or maybe provide some directions in case you can't.

Cheers,
Pedro

**Comment by zykh** [comment]
Thanks for reporting, @pcs-sossia.
Updated just now - let me know if you experience any regression.

**Comment by pedrocs-exo** [comment]
If you could just see the big smile in my face!!! Everything seems to be working well.

Grazie mille!

**Comment by zykh** [comment]
Di niente!
