### ISSUE TITLE
Not working in gnome 3.30

### ISSUE THREAD

**Issue by simplexe** [zykh/walNUT#2]
Hi Daniele, i have been using walNUT and find it quite useful. Thx for sharing! But ever since I upgraded to Gnome 3.30 the extension stopped working. Can you pls fix it? Or maybe provide some directions in case you can't.

Cheers, Semen

**Comment by zykh** [comment]
Ah, right, I forgot to push the changes to GitHub... and I can't access my local repository till Friday...
Meanwhile, if you don't care about compatibility with old versions of GNOME Shell, you should be able to make the extension work again by simply replacing the 4 'for each ... in' loops in `extension.js` (at line [601](https://github.com/zykh/walNUT/blob/master/extension.js#L601), [671](https://github.com/zykh/walNUT/blob/master/extension.js#L671), [3571](https://github.com/zykh/walNUT/blob/master/extension.js#L3571) and [3583](https://github.com/zykh/walNUT/blob/master/extension.js#L3583)) with 'for ... of' loops (just remove the 'each' word and substitute the 'in' word with 'of') and then restart the Shell.

**Comment by simplexe** [comment]
All works fine! Thx you!
